dist: trusty
 
language: R
warnings_are_errors: true

sudo: required

apt_packages:
  - gsl-bin
  - libgsl0-dbg
  - libgsl0-dev
  - libgsl0ldbl
  - libcurl4-openssl-dev
  - libxml2-dev
  - r-cran-vinecopula
  - r-cran-rcpp
  - r-cran-rcpparmadillo
  - r-cran-covr
  - r-cran-testthat
  - r-cran-locfit
  - r-cran-qrng
  - r-cran-quadprog

before_install:
  - sudo add-apt-repository ppa:marutter/c2d4u -y
  - sudo apt-get update -q

repos:
  CRAN: http://cran.rstudio.com

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
