language: R
warnings_are_errors: true

sudo: required

apt_packages:
  - gsl-bin
  - libgsl0-dbg
  - libgsl0-dev
  - libgsl0ldbl
  - libcurl4-openssl-dev
  - libxml2-dev


repos:
  CRAN: http://cran.rstudio.com

  r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
